#!/usr/bin/env python3
"""
JENNY SOP Generator - Backend Server
Flask API that orchestrates:
  1. File upload (template + draft)
  2. Phase 0 extraction (calls LLM API for config generation)
  3. Config sanitization
  4. Phase 1+ pipeline execution (deterministic)
  5. Output delivery (.docx download)
"""

import os, sys, json, shutil, tempfile, uuid, subprocess, re, traceback
from pathlib import Path
from datetime import datetime
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import urllib.request

app = Flask(__name__)
CORS(app)

# Configuration
UPLOAD_DIR = Path("./uploads")
JOBS_DIR = Path("./jobs")
PIPELINE_DIR = Path(__file__).parent
UPLOAD_DIR.mkdir(exist_ok=True)
JOBS_DIR.mkdir(exist_ok=True)

# API Key from environment -- NEVER hardcode this
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")

# Store uploaded files per session
sessions = {}


# ============================================================
# HELPERS
# ============================================================

def sanitize_config(config):
    """Fix common LLM extraction issues before pipeline runs."""
    issues = []

    # Ampersand encoding in titles
    for field in ["full_title", "short_title"]:
        if field in config and "&" in config[field] and "&amp;" not in config[field]:
            config[field] = config[field].replace("&", "&amp;")
            issues.append(f"Encoded & as &amp; in {field}")

    # Don't double-encode
    for field in ["full_title", "short_title"]:
        if field in config:
            while "&amp;amp;" in config[field]:
                config[field] = config[field].replace("&amp;amp;", "&amp;")
                issues.append(f"Fixed double-encoded ampersand in {field}")

    # Strip newlines from titles
    for field in ["full_title", "short_title"]:
        if field in config and "\n" in config[field]:
            config[field] = config[field].replace("\n", " ").strip()
            issues.append(f"Stripped newline from {field}")

    # Validate ilvl values
    if "s6_steps" in config:
        for i, step in enumerate(config["s6_steps"]):
            if not isinstance(step.get("ilvl"), int) or step["ilvl"] not in (0, 1, 2, 3):
                config["s6_steps"][i]["ilvl"] = 0
                issues.append(f"Reset invalid ilvl to 0 for step {i}")
            if "highlighted" not in step:
                config["s6_steps"][i]["highlighted"] = False

    # Validate structure_type
    if config.get("structure_type") not in ("single", "multi"):
        config["structure_type"] = "single"
        issues.append("Reset invalid structure_type to 'single'")

    # Ensure required fields exist
    defaults = {
        "author": "JENNY",
        "gen_date": datetime.now().strftime("%m/%d/%Y"),
        "s3_supersession": "This document does not supersede any existing FEMA doctrine.",
        "extraction_notes": [],
    }
    for k, v in defaults.items():
        if k not in config:
            config[k] = v
            issues.append(f"Added missing field: {k}")

    return config, issues


def write_config_py(config, path):
    """Write the config dict as a Python file the pipeline can import."""
    lines = ["# JENNY Config - Auto-generated by JENNY Frontend",
             f"# Generated: {datetime.now().isoformat()}",
             "",
             "JENNY_CONFIG = {"]

    for key, val in config.items():
        if isinstance(val, str):
            # Escape quotes in strings
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{key}": "{escaped}",')
        elif isinstance(val, list):
            if len(val) == 0:
                lines.append(f'    "{key}": [],')
            elif isinstance(val[0], dict):
                # s6_steps
                lines.append(f'    "{key}": [')
                for item in val:
                    text_esc = item["text"].replace("\\", "\\\\").replace('"', '\\"')
                    ilvl = item.get("ilvl", 0)
                    hl = item.get("highlighted", False)
                    hl_color = item.get("highlight_color", "yellow")
                    lines.append(f'        {{"text": "{text_esc}", "ilvl": {ilvl}, "highlighted": {hl}, "highlight_color": "{hl_color}"}},')
                lines.append("    ],")
            else:
                # string arrays
                lines.append(f'    "{key}": [')
                for item in val:
                    item_esc = str(item).replace("\\", "\\\\").replace('"', '\\"')
                    lines.append(f'        "{item_esc}",')
                lines.append("    ],")
        elif isinstance(val, bool):
            lines.append(f'    "{key}": {val},')
        elif isinstance(val, (int, float)):
            lines.append(f'    "{key}": {val},')
        else:
            lines.append(f'    "{key}": {json.dumps(val)},')

    lines.append("}")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def run_jenny_pipeline(config, template_path, output_path, job_dir):
    """Execute the JENNY pipeline in a job directory."""
    # Write config file
    config_path = job_dir / "jenny_config.py"
    write_config_py(config, config_path)

    # Copy pipeline files to job directory
    for f in ["jenny_pipeline.py", "unpack_docx.py", "pack_docx.py"]:
        src = PIPELINE_DIR / f
        if src.exists():
            shutil.copy2(src, job_dir / f)

    # Copy template
    shutil.copy2(template_path, job_dir / "TEMPLATE.docx")

    # Run pipeline
    result = subprocess.run(
        [sys.executable, "jenny_pipeline.py",
         "jenny_config.py",
         "TEMPLATE.docx",
         "OUTPUT.docx"],
        capture_output=True, text=True, cwd=str(job_dir),
        timeout=120,
    )

    output_file = job_dir / "OUTPUT.docx"

    return {
        "success": result.returncode == 0 and output_file.exists(),
        "stdout": result.stdout,
        "stderr": result.stderr,
        "output_path": str(output_file) if output_file.exists() else None,
        "returncode": result.returncode,
    }


# ============================================================
# API ENDPOINTS
# ============================================================

@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "version": "JENNY v13 Backend"})


@app.route("/api/upload", methods=["POST"])
def upload():
    """Upload template and/or draft files. Returns a session ID."""
    session_id = request.form.get("session_id") or str(uuid.uuid4())

    if session_id not in sessions:
        sessions[session_id] = {"template": None, "draft": None}

    session_dir = UPLOAD_DIR / session_id
    session_dir.mkdir(exist_ok=True)

    for field in ["template", "draft"]:
        if field in request.files:
            f = request.files[field]
            path = session_dir / f"{field}.docx"
            f.save(str(path))
            sessions[session_id][field] = str(path)

    return jsonify({
        "session_id": session_id,
        "template": sessions[session_id]["template"] is not None,
        "draft": sessions[session_id]["draft"] is not None,
    })


@app.route("/api/extract", methods=["POST"])
def extract():
    """Phase 0: Extract draft text and call LLM for config generation. All server-side."""
    data = request.json
    session_id = data.get("session_id")

    if not session_id or session_id not in sessions:
        return jsonify({"error": "Invalid session"}), 400

    draft_path = sessions[session_id].get("draft")
    if not draft_path or not os.path.exists(draft_path):
        return jsonify({"error": "No draft uploaded"}), 400

    if not ANTHROPIC_API_KEY:
        return jsonify({"error": "ANTHROPIC_API_KEY not set in environment"}), 500

    # Extract text from docx
    import zipfile
    try:
        with zipfile.ZipFile(draft_path, 'r') as z:
            xml = z.read('word/document.xml').decode('utf-8')
        texts = re.findall(r'<w:t[^>]*>([^<]*)</w:t>', xml)
        draft_text = "\n".join(t for t in texts if t.strip())
    except Exception as e:
        return jsonify({"error": f"Failed to read draft: {e}"}), 500

    # Call Anthropic API
    system_msg = (
        "You are a document structure extractor. Your ONLY job is to read a source SOP draft "
        "and output a JSON config. You do NOT generate documents, modify templates, write XML, "
        "or make creative decisions.\n\n"
        "CRITICAL RULES:\n"
        "1. VERBATIM EXTRACTION - Copy text exactly. Do not fix spelling, grammar, capitalization, or punctuation.\n"
        "2. NO INVENTION - Every string must trace to the source document.\n"
        "3. PRESERVE HIERARCHY - ilvl 0 = main steps (1./2./3.), ilvl 1 = sub-steps (a./b./c.), ilvl 2 = sub-sub-steps (i./ii./iii.)\n"
        "4. AMPERSAND ENCODING - Encode & as &amp; ONLY in full_title and short_title.\n"
        "5. SECTIONS 4,5,7 are DERIVED from Section 6 content only.\n"
        "6. OUTPUT FORMAT - Return ONLY valid JSON. No markdown, no preamble, no explanation.\n"
        "7. If highlighted, also set \"highlight_color\" to the color name (\"yellow\", \"cyan\", etc.). Default is \"yellow\"."
    )

    gen_date = datetime.now().strftime("%m/%d/%Y")
    user_msg = (
        f"Read this SOP draft and extract into JSON:\n\n{draft_text[:12000]}\n\n"
        f"Return ONLY this JSON structure (no markdown fences):\n"
        "{\n"
        '  "full_title": "encode & as &amp;",\n'
        '  "short_title": "encode & as &amp;",\n'
        '  "structure_type": "single",\n'
        '  "cover_date": "",\n'
        '  "author": "JENNY",\n'
        f'  "gen_date": "{gen_date}",\n'
        '  "extraction_notes": [],\n'
        '  "purpose": "",\n'
        '  "scope": "",\n'
        '  "s6_intro": "",\n'
        '  "s6_steps": [{"text":"","ilvl":0,"highlighted":false}],\n'
        '  "s4_roles": ["Role: Description"],\n'
        '  "s5_materials": "Required materials and tools include: ...",\n'
        '  "s7_guidelines": ["guideline"],\n'
        '  "s3_supersession": "This document does not supersede any existing FEMA doctrine."\n'
        "}"
    )

    payload = json.dumps({
        "model": "claude-sonnet-4-6",
        "max_tokens": 4000,
        "system": system_msg,
        "messages": [{"role": "user", "content": user_msg}],
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            resp_data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8") if e.fp else ""
        return jsonify({"error": f"Anthropic API error {e.code}: {body[:300]}"}), 502
    except Exception as e:
        return jsonify({"error": f"API call failed: {e}"}), 502

    # Extract text from response
    text = "".join(b.get("text", "") for b in resp_data.get("content", []))

    # Parse JSON
    try:
        cleaned = text.replace("```json", "").replace("```", "").strip()
        config = json.loads(cleaned)
    except json.JSONDecodeError as e:
        return jsonify({
            "error": f"JSON parse failed: {e}",
            "raw_response": text[:2000],
        }), 422

    # Sanitize
    config, issues = sanitize_config(config)

    # Stats
    steps = config.get("s6_steps", [])
    stats = {
        "total_steps": len(steps),
        "ilvl0": sum(1 for s in steps if s.get("ilvl") == 0),
        "ilvl1": sum(1 for s in steps if s.get("ilvl") == 1),
        "ilvl2": sum(1 for s in steps if s.get("ilvl") == 2),
        "ilvl3": sum(1 for s in steps if s.get("ilvl") == 3),
        "highlighted": sum(1 for s in steps if s.get("highlighted")),
        "roles": len(config.get("s4_roles", [])),
        "guidelines": len(config.get("s7_guidelines", [])),
    }

    return jsonify({
        "config": config,
        "issues": issues,
        "stats": stats,
        "draft_chars": len(draft_text),
    })


@app.route("/api/sanitize", methods=["POST"])
def sanitize():
    """Sanitize an LLM-generated config before pipeline execution."""
    data = request.json
    config = data.get("config")
    if not config:
        return jsonify({"error": "No config provided"}), 400

    sanitized, issues = sanitize_config(config)

    # Compute stats
    steps = sanitized.get("s6_steps", [])
    stats = {
        "total_steps": len(steps),
        "ilvl0": sum(1 for s in steps if s.get("ilvl") == 0),
        "ilvl1": sum(1 for s in steps if s.get("ilvl") == 1),
        "ilvl2": sum(1 for s in steps if s.get("ilvl") == 2),
        "ilvl3": sum(1 for s in steps if s.get("ilvl") == 3),
        "highlighted": sum(1 for s in steps if s.get("highlighted")),
        "roles": len(sanitized.get("s4_roles", [])),
        "guidelines": len(sanitized.get("s7_guidelines", [])),
    }

    return jsonify({
        "config": sanitized,
        "issues": issues,
        "stats": stats,
    })


@app.route("/api/generate", methods=["POST"])
def generate():
    """Run the JENNY pipeline with a validated config. Returns the .docx."""
    data = request.json
    session_id = data.get("session_id")
    config = data.get("config")

    if not session_id or session_id not in sessions:
        return jsonify({"error": "Invalid session"}), 400
    if not config:
        return jsonify({"error": "No config provided"}), 400

    template_path = sessions[session_id].get("template")
    if not template_path or not os.path.exists(template_path):
        return jsonify({"error": "No template uploaded"}), 400

    # Create job directory
    job_id = str(uuid.uuid4())[:8]
    job_dir = JOBS_DIR / job_id
    job_dir.mkdir(exist_ok=True)

    try:
        result = run_jenny_pipeline(config, template_path, None, job_dir)

        if result["success"]:
            # Parse score from stdout
            score_match = re.search(r"SCORE:\s*(\d+)/(\d+)\s*\((\d+)%\)", result["stdout"])
            score = score_match.group(0) if score_match else "Unknown"

            return jsonify({
                "success": True,
                "job_id": job_id,
                "score": score,
                "log": result["stdout"],
                "download_url": f"/api/download/{job_id}",
            })
        else:
            return jsonify({
                "success": False,
                "log": result["stdout"],
                "error": result["stderr"],
            }), 500

    except subprocess.TimeoutExpired:
        return jsonify({"error": "Pipeline timed out (120s)"}), 504
    except Exception as e:
        return jsonify({"error": str(e), "traceback": traceback.format_exc()}), 500


@app.route("/api/download/<job_id>", methods=["GET"])
def download(job_id):
    """Download the generated .docx file."""
    output_path = JOBS_DIR / job_id / "OUTPUT.docx"
    if not output_path.exists():
        return jsonify({"error": "File not found"}), 404

    return send_file(
        str(output_path),
        mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        as_attachment=True,
        download_name=f"SOP_JENNY_{job_id}.docx",
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    print("JENNY SOP Generator Backend")
    print(f"  Pipeline dir: {PIPELINE_DIR}")
    print(f"  Upload dir:   {UPLOAD_DIR}")
    print(f"  Jobs dir:     {JOBS_DIR}")
    print()
    app.run(host="0.0.0.0", port=5000, debug=True)