#!/usr/bin/env python3
"""
JENNY SOP Generator - Backend Server

Flask API that orchestrates:
  1. File upload (template + draft)
  2. Draft text extraction (from .docx)
  3. Phase 0 extraction (LLM call -> config dict) [NEW: OpenAI Responses API]
  4. Config sanitization
  5. Phase 1+ pipeline execution (deterministic)
  6. Output delivery (.docx download)
"""

import os, sys, json, shutil, tempfile, uuid, subprocess, re, traceback
from pathlib import Path
from datetime import datetime
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS

# Optional dependency: only required if you use /api/phase0
try:
    from openai import OpenAI
except Exception:
    OpenAI = None  # Will be checked at runtime

app = Flask(__name__)
CORS(app)

# Configuration
UPLOAD_DIR = Path("./uploads")
JOBS_DIR = Path("./jobs")
PIPELINE_DIR = Path(__file__).parent  # Where jenny_pipeline.py lives
UPLOAD_DIR.mkdir(exist_ok=True)
JOBS_DIR.mkdir(exist_ok=True)

# Store uploaded files per session
sessions = {}


# ============================================================
# HELPERS
# ============================================================

def extract_docx_text(docx_path: str) -> str:
    """Extract plain text from a .docx by reading word/document.xml."""
    import zipfile
    with zipfile.ZipFile(docx_path, "r") as z:
        xml = z.read("word/document.xml").decode("utf-8", errors="replace")
    texts = re.findall(r"<w:t[^>]*>([^<]*)</w:t>", xml)
    return "\n".join(t for t in texts if t.strip())


def sanitize_config(config):
    """Fix common LLM extraction issues before pipeline runs."""
    issues = []

    # Ampersand encoding in titles
    for field in ["full_title", "short_title"]:
        if field in config and "&" in config[field] and "&amp;" not in config[field]:
            config[field] = config[field].replace("&", "&amp;")
            issues.append(f"Encoded & as &amp; in {field}")

    # Don't double-encode
    for field in ["full_title", "short_title"]:
        if field in config:
            while "&amp;amp;" in config[field]:
                config[field] = config[field].replace("&amp;amp;", "&amp;")
                issues.append(f"Fixed double-encoded ampersand in {field}")

    # Strip newlines from titles
    for field in ["full_title", "short_title"]:
        if field in config and "\n" in config[field]:
            config[field] = config[field].replace("\n", " ").strip()
            issues.append(f"Stripped newline from {field}")

    # Validate ilvl values
    if "s6_steps" in config:
        for i, step in enumerate(config["s6_steps"]):
            if not isinstance(step.get("ilvl"), int) or step["ilvl"] not in (0, 1, 2):
                config["s6_steps"][i]["ilvl"] = 0
                issues.append(f"Reset invalid ilvl to 0 for step {i}")
            if "highlighted" not in step:
                config["s6_steps"][i]["highlighted"] = False

    # Validate structure_type
    if config.get("structure_type") not in ("single", "multi"):
        config["structure_type"] = "single"
        issues.append("Reset invalid structure_type to 'single'")

    # Ensure required fields exist
    defaults = {
        "author": "JENNY-v13",
        "gen_date": datetime.now().strftime("%m/%d/%Y"),
        "s3_supersession": "This document does not supersede any existing FEMA doctrine.",
        "extraction_notes": [],
    }
    for k, v in defaults.items():
        if k not in config:
            config[k] = v
            issues.append(f"Added missing field: {k}")

    return config, issues


def write_config_py(config, path):
    """Write the config dict as a Python file the pipeline can import."""
    lines = [
        "# JENNY Config - Auto-generated by JENNY Backend",
        f"# Generated: {datetime.now().isoformat()}",
        "",
        "JENNY_CONFIG = {",
    ]

    for key, val in config.items():
        if isinstance(val, str):
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{key}": "{escaped}",')
        elif isinstance(val, list):
            if len(val) == 0:
                lines.append(f'    "{key}": [],')
            elif isinstance(val[0], dict):
                lines.append(f'    "{key}": [')
                for item in val:
                    text_esc = str(item.get("text", "")).replace("\\", "\\\\").replace('"', '\\"')
                    ilvl = item.get("ilvl", 0)
                    hl = item.get("highlighted", False)
                    lines.append(f'        {{"text": "{text_esc}", "ilvl": {ilvl}, "highlighted": {hl}}},')
                lines.append("    ],")
            else:
                lines.append(f'    "{key}": [')
                for item in val:
                    item_esc = str(item).replace("\\", "\\\\").replace('"', '\\"')
                    lines.append(f'        "{item_esc}",')
                lines.append("    ],")
        elif isinstance(val, bool):
            lines.append(f'    "{key}": {val},')
        elif isinstance(val, (int, float)):
            lines.append(f'    "{key}": {val},')
        else:
            lines.append(f'    "{key}": {json.dumps(val)},')

    lines.append("}")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def run_jenny_pipeline(config, template_path, output_path, job_dir):
    """Execute the JENNY pipeline in a job directory."""
    config_path = job_dir / "jenny_config.py"
    write_config_py(config, config_path)

    # Copy pipeline files to job directory
    for f in ["jenny_pipeline.py", "unpack_docx.py", "pack_docx.py"]:
        src = PIPELINE_DIR / f
        if src.exists():
            shutil.copy2(src, job_dir / f)

    # Copy template
    shutil.copy2(template_path, job_dir / "TEMPLATE.docx")

    # Run pipeline
    result = subprocess.run(
        [sys.executable, "jenny_pipeline.py", "jenny_config.py", "TEMPLATE.docx", "OUTPUT.docx"],
        capture_output=True,
        text=True,
        cwd=str(job_dir),
        timeout=120,
    )

    output_file = job_dir / "OUTPUT.docx"

    return {
        "success": result.returncode == 0 and output_file.exists(),
        "stdout": result.stdout,
        "stderr": result.stderr,
        "output_path": str(output_file) if output_file.exists() else None,
        "returncode": result.returncode,
    }


def _strip_code_fences(s: str) -> str:
    s = s.strip()
    if s.startswith("```") and s.endswith("```"):
        s = re.sub(r"^```[a-zA-Z0-9_-]*\s*", "", s)
        s = re.sub(r"\s*```$", "", s)
    return s.strip()


def _coerce_json_object(s: str) -> dict:
    """Best-effort: extract the first top-level JSON object from a string."""
    s = _strip_code_fences(s)
    try:
        return json.loads(s)
    except Exception:
        pass

    first = s.find("{")
    last = s.rfind("}")
    if first == -1 or last == -1 or last <= first:
        raise ValueError("Model output did not contain a JSON object.")
    candidate = s[first:last+1]
    return json.loads(candidate)


def run_phase0_openai(draft_text: str) -> dict:
    """
    Run Phase 0 extraction using OpenAI Responses API and return a config dict.

    Environment variables:
      - OPENAI_API_KEY (required)
      - OPENAI_MODEL (optional, default: gpt-4.1)
      - OPENAI_TEMPERATURE (optional, default: 0)
    """
    if OpenAI is None:
        raise RuntimeError("Missing dependency: openai. Install with 'pip install openai'.")

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set.")

    model = os.environ.get("OPENAI_MODEL", "gpt-4.1")
    try:
        temperature = float(os.environ.get("OPENAI_TEMPERATURE", "0"))
    except Exception:
        temperature = 0.0

    prompt_path = PIPELINE_DIR / "JENNY_Phase0_Extraction_Prompt.md"
    if not prompt_path.exists():
        raise RuntimeError(f"Missing Phase 0 prompt: {prompt_path}")

    system_prompt = prompt_path.read_text(encoding="utf-8")

    client = OpenAI(api_key=api_key)

    resp = client.responses.create(
        model=model,
        temperature=temperature,
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": draft_text},
        ],
    )

    raw_text = getattr(resp, "output_text", None)
    if raw_text is None:
        raw_text = json.dumps(resp.model_dump(), ensure_ascii=False)

    config = _coerce_json_object(raw_text)
    return {
        "config": config,
        "raw": raw_text,
        "model": model,
    }


# ============================================================
# API ENDPOINTS
# ============================================================

@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({
        "status": "ok",
        "version": "JENNY v13 Backend",
        "has_openai_sdk": OpenAI is not None,
        "openai_model": os.environ.get("OPENAI_MODEL", "gpt-4.1"),
    })


@app.route("/api/upload", methods=["POST"])
def upload():
    """Upload template and/or draft files. Returns a session ID."""
    session_id = request.form.get("session_id") or str(uuid.uuid4())

    if session_id not in sessions:
        sessions[session_id] = {"template": None, "draft": None}

    session_dir = UPLOAD_DIR / session_id
    session_dir.mkdir(exist_ok=True)

    for field in ["template", "draft"]:
        if field in request.files:
            f = request.files[field]
            path = session_dir / f"{field}.docx"
            f.save(str(path))
            sessions[session_id][field] = str(path)

    return jsonify({
        "session_id": session_id,
        "template": sessions[session_id]["template"] is not None,
        "draft": sessions[session_id]["draft"] is not None,
    })


@app.route("/api/extract", methods=["POST"])
def extract():
    """Extract draft text for Phase 0. Returns raw text."""
    data = request.json or {}
    session_id = data.get("session_id")

    if not session_id or session_id not in sessions:
        return jsonify({"error": "Invalid session"}), 400

    draft_path = sessions[session_id].get("draft")
    if not draft_path or not os.path.exists(draft_path):
        return jsonify({"error": "No draft uploaded"}), 400

    try:
        draft_text = extract_docx_text(draft_path)
    except Exception as e:
        return jsonify({"error": f"Failed to read draft: {e}"}), 500

    return jsonify({
        "draft_text": draft_text,
        "char_count": len(draft_text),
    })


@app.route("/api/phase0", methods=["POST"])
def phase0():
    """
    Run Phase 0 extraction on the server using OpenAI.

    Request JSON supports either:
      - {"session_id": "..."}  (reads uploaded draft)
      - {"draft_text": "..."}  (uses provided text)

    Response:
      - {"config": {...}, "raw": "...", "model": "..."}
    """
    data = request.json or {}
    session_id = data.get("session_id")
    draft_text = data.get("draft_text")

    if session_id:
        if session_id not in sessions:
            return jsonify({"error": "Invalid session"}), 400
        draft_path = sessions[session_id].get("draft")
        if not draft_path or not os.path.exists(draft_path):
            return jsonify({"error": "No draft uploaded"}), 400
        try:
            draft_text = extract_docx_text(draft_path)
        except Exception as e:
            return jsonify({"error": f"Failed to read draft: {e}"}), 500

    if not draft_text or not isinstance(draft_text, str) or not draft_text.strip():
        return jsonify({"error": "No draft_text provided"}), 400

    try:
        result = run_phase0_openai(draft_text)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e), "traceback": traceback.format_exc()}), 500


@app.route("/api/sanitize", methods=["POST"])
def sanitize():
    """Sanitize an LLM-generated config before pipeline execution."""
    data = request.json or {}
    config = data.get("config")
    if not config:
        return jsonify({"error": "No config provided"}), 400

    sanitized, issues = sanitize_config(config)

    steps = sanitized.get("s6_steps", [])
    stats = {
        "total_steps": len(steps),
        "ilvl0": sum(1 for s in steps if s.get("ilvl") == 0),
        "ilvl1": sum(1 for s in steps if s.get("ilvl") == 1),
        "ilvl2": sum(1 for s in steps if s.get("ilvl") == 2),
        "highlighted": sum(1 for s in steps if s.get("highlighted")),
        "roles": len(sanitized.get("s4_roles", [])),
        "guidelines": len(sanitized.get("s7_guidelines", [])),
    }

    return jsonify({
        "config": sanitized,
        "issues": issues,
        "stats": stats,
    })


@app.route("/api/generate", methods=["POST"])
def generate():
    """Run the JENNY pipeline with a validated config. Returns the .docx."""
    data = request.json or {}
    session_id = data.get("session_id")
    config = data.get("config")

    if not session_id or session_id not in sessions:
        return jsonify({"error": "Invalid session"}), 400
    if not config:
        return jsonify({"error": "No config provided"}), 400

    template_path = sessions[session_id].get("template")
    if not template_path or not os.path.exists(template_path):
        return jsonify({"error": "No template uploaded"}), 400

    # Create job directory
    job_id = str(uuid.uuid4())[:8]
    job_dir = JOBS_DIR / job_id
    job_dir.mkdir(exist_ok=True)

    try:
        result = run_jenny_pipeline(config, template_path, None, job_dir)

        if result["success"]:
            score_match = re.search(r"SCORE:\s*(\d+)/(\d+)\s*\((\d+)%\)", result["stdout"])
            score = score_match.group(0) if score_match else "Unknown"

            return jsonify({
                "success": True,
                "job_id": job_id,
                "score": score,
                "log": result["stdout"],
                "download_url": f"/api/download/{job_id}",
            })
        else:
            return jsonify({
                "success": False,
                "log": result["stdout"],
                "error": result["stderr"],
            }), 500

    except subprocess.TimeoutExpired:
        return jsonify({"error": "Pipeline timed out (120s)"}), 504
    except Exception as e:
        return jsonify({"error": str(e), "traceback": traceback.format_exc()}), 500


@app.route("/api/download/<job_id>", methods=["GET"])
def download(job_id):
    """Download the generated .docx file."""
    output_path = JOBS_DIR / job_id / "OUTPUT.docx"
    if not output_path.exists():
        return jsonify({"error": "File not found"}), 404

    return send_file(
        str(output_path),
        mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        as_attachment=True,
        download_name=f"SOP_JENNY_{job_id}.docx",
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    print("JENNY SOP Generator Backend")
    print(f"  Pipeline dir: {PIPELINE_DIR}")
    print(f"  Upload dir:   {UPLOAD_DIR}")
    print(f"  Jobs dir:     {JOBS_DIR}")
    print()
    app.run(host="0.0.0.0", port=5000, debug=True)